--Script generated by GroveW

yPos = 0.0
attackConnected = false
newPos = {x, y, z}
startPosition = {x, y, z}
distance = 1.0
shakeTime = 0.05
returnTime = 0.05
shaking = false
shakeCo = {}

function cameraStart()
    x, yPos, z = getTransform(entity, componentManager)
end

function cameraUpdate(dt)
    if shaking == false then
        setTransform(entity, componentManager, player.position.x, yPos, player.position.z)
    else
        coroutine.resume(shakeCo, dt)
    end
end

function shake()
    shaking = true
    tempShakeTime = time;
    math.randomseed(time)
    local x = math.random(1, 200)
    x = x / 100.0 - 1.0
    math.randomseed(time)
    local y = math.random(100, 200)
    y = y / 100.0 - 1.0
    local randPos = {x = x, y = y}

    newPos.x = x
    newPos.y = yPos
    newPos.z = y         

    shakeCo = coroutine.create(shakeCoroutine, 0.0)
end

function shakeCoroutine(dt)
    while time - tempShakeTime < shakeTime do
        local x, y, z = getTransform(entity, componentManager)
        setTransform(entity, componentManager, x + (newPos.x * dt * 5.0), yPos, z + (newPos.z * dt * 5.0))
        dt = coroutine.yield()
    end

    tempReturnTime = time

    while time - tempReturnTime < returnTime do
        local x, y, z = getTransform(entity, componentManager)
        setTransform(entity, componentManager, x - (newPos.x * dt * 5.0), yPos, z - (newPos.z * dt * 5.0))
        dt = coroutine.yield()
    end

    shaking = false
end