--Script generated by GroveW

yPos = 0.0

function cameraStart()
    x, yPos, z = getTransform(entity, componentManager)
end

function cameraUpdate(dt)
    setTransform(entity, componentManager, player.position.x, yPos, player.position.z)
end
