--Script generated by GroveW

combos = { ["whirlwind"] = {"SA", "LA", "LD"},
           ["dash1"]      = {"LL", "LL", "SR"},
           ["dash2"]      = {"LR", "LR", "SL"}}

function combosStart()
end

function combosUpdate(dt)
end

function whirlwindCoroutine(dt)
    detectedCombo = "whirlwind"
    setBoundingBox(fists[1], componentManager, true)
    setBoundingBox(fists[2], componentManager, true)
    leftFist.attackTimeStamp = time
    rightFist.attackTimeStamp = time
    leftFist.damage = comboDamage * damageMultiplier
    rightFist.damage = comboDamage * damageMultiplier

    while leftFist.positionRel.z < 1.5 and rightFist.positionRel.z < 1.5 do
        if leftFist.positionRel.z < 1.5 then
            leftFist.positionRel.z = leftFist.positionRel.z + (80.0 * dt)
            setTransformRelToRotatingParent(fists[1], componentManager, player.position.x, player.position.y, player.position.z, 
            leftFist.positionRel.x, leftFist.positionRel.y, leftFist.positionRel.z,
            player.rotation.x, player.rotation.y, player.rotation.z)
        end
        if rightFist.positionRel.z < 1.5 then
            rightFist.positionRel.z = rightFist.positionRel.z + (80.0 * dt)
            setTransformRelToRotatingParent(fists[2], componentManager, player.position.x, player.position.y, player.position.z, 
            rightFist.positionRel.x, rightFist.positionRel.y, rightFist.positionRel.z,
            player.rotation.x, player.rotation.y, player.rotation.z)
        end
        dt = coroutine.yield()
    end
    leftFist.positionRel.z = 1.5
    rightFist.positionRel.z = 1.5

    setBoundingBoxDepth(fists[1], componentManager, defaultDepth, defaultDepth + 2.0)
    setBoundingBoxDepth(fists[2], componentManager, defaultDepth, defaultDepth + 2.0)

    local startingRotY = player.rotation.y
    local rotationY = startingRotY

    repeat
        rotationY = rotationY + (1440.0 * dt)
        setTransformRelToRotatingParent(fists[1], componentManager, player.position.x, player.position.y, player.position.z, 
        leftFist.positionRel.x, leftFist.positionRel.y, leftFist.positionRel.z,
        player.rotation.x, rotationY, player.rotation.z)
        setTransformRelToRotatingParent(fists[2], componentManager, player.position.x, player.position.y, player.position.z, 
        rightFist.positionRel.x, rightFist.positionRel.y, rightFist.positionRel.z,
        player.rotation.x, rotationY, player.rotation.z)
        dt = coroutine.yield()
    until rotationY - 360 > startingRotY
    setTransformRelToRotatingParent(fists[1], componentManager, player.position.x, player.position.y, player.position.z, 
        leftFist.positionRel.x, leftFist.positionRel.y, leftFist.positionRel.z,
        player.rotation.x, startingRotY, player.rotation.z)
    setTransformRelToRotatingParent(fists[2], componentManager, player.position.x, player.position.y, player.position.z, 
        rightFist.positionRel.x, rightFist.positionRel.y, rightFist.positionRel.z,
        player.rotation.x, startingRotY, player.rotation.z)

    setBoundingBoxDepth(fists[1], componentManager, defaultDepth, defaultDepth)
    setBoundingBoxDepth(fists[2], componentManager, defaultDepth, defaultDepth)

    while leftFist.positionRel.z > 0.4 and rightFist.positionRel.z > 0.4 do
        leftFist.positionRel.z = leftFist.positionRel.z - (40.0 * dt)
        rightFist.positionRel.z = rightFist.positionRel.z - (40.0 * dt)
        setTransformRelToRotatingParent(fists[1], componentManager, player.position.x, player.position.y, player.position.z, 
            leftFist.positionRel.x, leftFist.positionRel.y, leftFist.positionRel.z,
            player.rotation.x, player.rotation.y, player.rotation.z)
        setTransformRelToRotatingParent(fists[2], componentManager, player.position.x, player.position.y, player.position.z, 
            rightFist.positionRel.x, rightFist.positionRel.y, rightFist.positionRel.z,
            player.rotation.x, player.rotation.y, player.rotation.z)
        dt = coroutine.yield()
    end
    leftFist.positionRel.z = 0.4
    rightFist.positionRel.z = 0.4

    setBoundingBox(fists[1], componentManager, false)
    setBoundingBox(fists[2], componentManager, false)
    leftFist.damage = lightDamage * damageMultiplier
    rightFist.damage = lightDamage * damageMultiplier

    detectedCombo = "none"
end

function dashCoroutine(dt)
    detectedCombo = "dash"
    setBoundingBox(fists[1], componentManager, true)
    setBoundingBox(fists[2], componentManager, true)
    setTrigger(player.entity, componentManager, true)
    leftFist.attackTimeStamp = time
    rightFist.attackTimeStamp = time
    leftFist.damage = comboDamage * damageMultiplier
    rightFist.damage = comboDamage * damageMultiplier

    applyForce(player.entity, componentManager, (-mouse.x), 0.0, 
        (-mouse.z), -1000.0)

    local timeStamp = time
    
    while time - timeStamp < 0.2 do
        setPositionRelativeToPlayer(leftFist)
        setPositionRelativeToPlayer(rightFist)
        dt = coroutine.yield()
    end

    setBoundingBox(fists[1], componentManager, false)
    setBoundingBox(fists[2], componentManager, false)
    setTrigger(player.entity, componentManager, false)
    leftFist.damage = lightDamage * damageMultiplier
    rightFist.damage = lightDamage * damageMultiplier

    detectedCombo = "none"
end