--Script generated by GroveW

equipment = { ["E"] = nil, ["Q"] = nil }

function equipmentStart()
end

function equipmentUpdate(dt)
    drawEQ()
    handleEQInput()
end

function eqFull()
    if equipment["E"] ~= nil and equipment["Q"] ~= nil then
        return true
    end

    return false
end

function addToEquipment(type)
    local freeSlot = equipment["E"] == nil and "E" or "Q"
    equipment[freeSlot] = type
end

function drawEQ()
    --print("E", equipment["E"], "Q", equipment["Q"])
    --draw slots depending if they are empty or not
end

function handleEQInput()
    if ePressed == true and equipment["Q"] ~= nil then
        getHigh(equipment["Q"])
        equipment["Q"] = nil
    end

    if qPressed == true and equipment["E"] ~= nil then
        getHigh(equipment["E"])
        equipment["E"] = nil
    end
end