#!/bin/bash

file="$1.lua"

if [ -e $file ]; then
  echo "Script $file already exists!"
else
  user=$(git config user.name)
  echo "--Script generated by $user"$'\n' > $file

  echo "function $1Start()" >> $file
  echo "end"$'\n' >> $file

  echo "function $1Update(dt)" >> $file
  echo "end" >> $file
fi