--Script generated by GroveW

function pillBlueStart()
end

function pillBlueUpdate(dt)
end

function pillBlueOnCollisionEnter(box)
    if getTag(box) == "player" then
        consume("blue")
    end
end