--Script generated by GroveW

function pillRedStart()
end

function pillRedUpdate(dt)
end

function consume(type)
    getHigh(type)
    destroyEntity(gameplayManager, entity)
end

function pillRedOnCollisionEnter(box)
    if getTag(box) == "player" then
        consume("red")
    end
end