--Script generated by GroveW

positionRel = {x = 0.0, y = 0.0, z = 3.0}
attackTimeStamp = 0.0
isAttacking = false

function weaponStart()
    setBoundingBox(entity, componentManager, false)
end

function weaponUpdate(dt)
    setPositionRelativeToPlayer()
    handleAttack(dt)
end

function setPositionRelativeToPlayer()
    setTransformRelToRotatingParent(entity, componentManager, player.position.x, player.position.y, player.position.z, 
    positionRel.x, positionRel.y, positionRel.z,
    player.rotation.x, player.rotation.y, player.rotation.z)
end

function handleAttack(dt)
    if isAttacking == false and leftMousePressed == true then
        attackTimeStamp = time
        isAttacking = true
        attackCo = coroutine.create(attackCoroutine)
        coroutine.resume( attackCo, dt )
    elseif isAttacking == true then
        coroutine.resume( attackCo, dt )
    end
    
end

function attackCoroutine(dt)

    setBoundingBox(entity, componentManager, true)

    while time - attackTimeStamp < 0.1 do
        positionRel.z = lerp(3.0, 6.0, (time - attackTimeStamp) / 0.1)
        dt = coroutine.yield()
    end
    positionRel.z = 6.0

    attackTimeStamp = time

    while time - attackTimeStamp < 0.1 do
        dt = coroutine.yield()
    end

    attackTimeStamp = time
    setBoundingBox(entity, componentManager, false)

    while time - attackTimeStamp < 0.2 do
        positionRel.z = lerp(6.0, 3.0, (time - attackTimeStamp) / 0.2)
        dt = coroutine.yield()
    end
    positionRel.z = 3.0
    
    isAttacking = false
end

function lerp(p0, p1, t)
    return (1 - t) * p0 + t * p1
end